server:
  port: 8080
auth:
  host: https://turnstile.server.d0lim.com
  path:
    login: /api/v1/auth/login
    callback: /api/v1/auth/callback
  redirectUri: http://localhost:8080/api/v1/auth/callback