name: ci-dev

on:
  push:
    branches:
      - 'master'
jobs:
  docker-build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: export environment
#        run: |
#          touch ./.env
#          echo "${{ secrets.ENV }}" >> ./.env
#          source ./.env
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_ID }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.REGISTRY_HOST }}/tarae:latest